feat: add docker layer caching support on machine executors
CircleCI-Public/circleci-config-sdk-ts pull request #147
Opened 2022-09-22 08:22 UTC by a-cordier

see https://github.com/CircleCI-Public/circleci-config-sdk-ts/issues/146

2022-09-27 16:18 UTC, KyleTryon commented
Hey @a-cordier Thanks for the contribution!
I see here the Docker Layer Caching boolean was added to the machine executor type.

Docker Layer Caching is actually available on the Docker Container as well: https://circleci.com/docs/docker-layer-caching

We _probably_ could do some very advanced typescript stuff to make it so that you require the `setup_remote_docker` step on the docker-based job implementing DLC, but i think for now we could potentially get away with adding the boolean  to the parent `Executor` class and extend it down to both.

CC @Jaryt for opinion as well.

2022-09-29 12:54 UTC, a-cordier commented
@KyleTryon Thanks for the prompt review ! Does the docker_layer_caching property applies to (MacOS|Windows) executors ? I can see that they both extend the Executor class.

2022-09-29 13:23 UTC, a-cordier commented
Just figured out that dlc is implemented with a command for docker executors.

I've updated the PR to add dlc support on the command as well

2022-09-29 13:57 UTC, KyleTryon reviewed
Well done 👏 . And thank you for looking into the config reference to resolve this. I had to double check that myself. I am starting the tests now.

edit: oops, just noticed the branch is out of date. Going to update that first, fingers crossed for no conflicts

2022-09-29 14:06 UTC, KyleTryon requested changes
This should resolve the linting errors. Minor differences between JSDoc and TSDoc.
https://app.circleci.com/pipelines/github/CircleCI-Public/circleci-config-sdk-ts/439/workflows/7a9acf7c-28ec-410e-9a49-46888efbb375/jobs/2299

2022-09-29 14:06 UTC, KyleTryon commented on src/lib/Components/Commands/exports/Native/SetupRemoteDocker.ts
> +   * @param {boolean} enabled - If true, docker layer caching is enabled for the job.
```suggestion
   * @param enabled - If true, docker layer caching is enabled for the job.
```

In typescript, the type is automatically inferred here.

2022-09-29 14:06 UTC, KyleTryon commented on src/lib/Components/Commands/exports/Native/SetupRemoteDocker.ts
> +   * @returns {SetupRemoteDocker} - The current instance of the SetupRemoteDocker Command.
```suggestion
   * @returns SetupRemoteDocker - The current instance of the SetupRemoteDocker Command.
```

2022-09-29 14:13 UTC, KyleTryon commented on src/lib/Components/Executors/exports/MachineExecutor.ts
> +   * @param {boolean} enabled - If true, docker layer caching is enabled for the machine executor.
```suggestion
   * @param enabled - If true, docker layer caching is enabled for the machine executor.
```

2022-09-29 14:21 UTC, merged